export type StackParams = {
  Welcome: undefined;
  OnBoarding: undefined;
  Login: undefined;
  SignUp: undefined;
  SetUp: undefined;
  ForgottenPassword: undefined;
  EnterOtp: undefined;
  SetPassword: undefined;
  Gender: undefined;
  Age: undefined;
  Weight: undefined;
  Height: undefined;
  Goal: undefined;
  PhysicalActivityLevel: undefined;
  YourProfile: undefined;
  Home: undefined;
  AppTab: undefined;
  UserProfile: undefined;
  MyProfile: undefined;
  Favorites: undefined;
  Setting: undefined;
  NotificationsSetting: undefined;
};
